# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: FirstsStage
  displayName: FirstsStage
  jobs:
  - job: FirstJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

- stage: SecondStage
  displayName: AZURECLITASK
  jobs:
  - job: AZURECLITASK
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial (fde3182a-e7a8-4643-bd4e-6d0aebf183d0)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az group create -l westus -n MyTestResourceGroup'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial (fde3182a-e7a8-4643-bd4e-6d0aebf183d0)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az group exists -n MyTestResourceGroup'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial (fde3182a-e7a8-4643-bd4e-6d0aebf183d0)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az group list'
